### ISSUE TITLE
Ignore generated-sources

### ISSUE THREAD

**Issue by daniel-shuy** [societe-generale/arch-unit-maven-plugin#33]
## Summary

Currently the predefined rules are also scanning class files in `generated-sources`, which I have no control over. Is there a way to configure the plugin to ignore `generated-sources`?

## Type of Issue
It is a : 
 - [ ] bug
 - [x] request
 - [ ] question regarding the documentation

## Motivation
I don't have any control over the class files generated in `generated-sources`, thus have no way to resolve violations in the generated class files.

**Comment by vincent-fuchs** [comment]
Thanks for this request ! 

Indeed, it could be interesting to set have an optional parameter in the config, to give a list of folders to ignore. We would have to implement it in https://github.com/societe-generale/arch-unit-build-plugin-core though.

I faced the exact same issue, but found a workaround. Maybe it's not the same issue, but I'll mention the workaround anyway : 

By default, Lombok will generate getters on collections that don't have the javax.annotation.Nonnull annotation. And I had DontReturnNullCollectionTest rule raising violations. 

To avoid this, I found 2 solutions : 
- write the getter yourself for these fields : in that case you can make sure that null is never returned by testing it before returning the value, and returning an empty list if it is. 

- tweak the Lombok annotation, as described here : https://projectlombok.org/features/experimental/onX 

```java
     @Getter(onMethod_={@Nonnull})
```

But in that case, I am quite sure it's still possible that null is returned, even though the annotation says otherwise - so it may be misleading.

**Comment by daniel-shuy** [comment]
Thanks. Unfortunately my issue is not with Lombok, but [MapStruct](https://mapstruct.org/), which has no way of configuring the generated methods.

**Comment by vincent-fuchs** [comment]
fixed in v2.4.0

**Comment by daniel-shuy** [comment]
Still having this issue with `arch-unit-maven-plugin` `2.4.0` and `arch-unit-build-plugin-core` `2.5.2`. Is there anything that I have to configure specifically?

**Comment by vincent-fuchs** [comment]
yes, I've added a new config parameter (see the documentation) : 

    <excludedPaths>
        <excludedPath>generated-sources</excludedPath>
    </excludedPaths>

**Comment by daniel-shuy** [comment]
Just tried with that, seems like it doesn't work either. It only seems to match the package name or class name, not the full path.

**Comment by vincent-fuchs** [comment]
> 
> 
> Just tried with that, seems like it doesn't work either. It only seems to match the package name or class name, not the full path.

archUnit looks at the compiled code, not the source code. Do you know in which folder your generated-sources code gets compiled ? you could try to configure this directory instead

**Comment by daniel-shuy** [comment]
> archUnit looks at the compiled code, not the source code

Oh right, I forgot about that. Looks like there's no way I can just ignore all classes in `generated-sources`, as they are all combined in the same package under `target`. The most I can do is to group all the MapStruct classes in the same package and ignore the package. Thanks.

**Comment by vincent-fuchs** [comment]
maybe you can change that behavior by tweaking the maven-compile plugin... but not sure !
